### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by Sicks3c** [Acceis/leakScraper#6]
**Hey**

_Im using kali 2_

I followed the install process When I launch the script
``` python3 leakScraper.py ```

All works good no syntax error but when I visit 
> localhost:8080

I get this error
```Bottle v0.12.17 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.

leakScraper.py:58: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere
  count = credentials.count()
```

any solution ?

**Comment by almandin** [comment]
Looks like pymongo deprecated the count() method. I'm currently benchmarking the new count_documents() to see if its efficient enough.

**Comment by almandin** [comment]
Can you tell me if you have this warning when doing a query ? At startup it looks the number of credentials available but it also calls the method count when researching for a specific domain. I don't have any warning in either cases :/

**Comment by Sicks3c** [comment]
Hello @almandin 
This is the message that I get this
```
127.0.0.1 - - [10/May/2020 01:47:32] "GET /robots.txt HTTP/1.1" 404 740
leakScraper.py:58: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere
  count = credentials.count()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.7/dist-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/dist-packages/bottle.py", line 3650, in wrapper
    result = func(*args, **kwargs)
  File "leakScraper.py", line 58, in index
    count = credentials.count()
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 1800, in count
    return self._count(cmd, collation, session)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 1600, in _count
    _cmd, self._read_preference_for(session), session)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/mongo_client.py", line 1454, in _retryable_read
    read_pref, session, address=address)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/mongo_client.py", line 1253, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
127.0.0.1 - - [10/May/2020 01:48:02] "GET / HTTP/1.1" 500 741
127.0.0.1 - - [10/May/2020 01:48:02] "GET /favicon.ico HTTP/1.1" 404 742
```

![Screenshot from 2020-05-10 01-48-54](https://user-images.githubusercontent.com/32225186/81488418-7410df80-9260-11ea-962c-60a0cef3e966.png)
In the terminal 
Meanwhile in the browser I have this
![Screenshot from 2020-05-10 01-49-46](https://user-images.githubusercontent.com/32225186/81488429-8b4fcd00-9260-11ea-9c47-4a7b058ae5e6.png)

**Comment by almandin** [comment]
Your error (500 internal error) is not due to the deprecation warning. You have a connection refused from the mongo server (is it up and running ?)
I'm pretty sure I already fixed something about this deprecation warning, I'll take a look about it.

**Comment by Sicks3c** [comment]
Hello @almandin 
Can you tell me how to run the mongo server ?
I guess that's what seems the issue
Regards

**Comment by almandin** [comment]
`systemctl start mongod` on a modern linux system.
Can you tell me what version of the pymongo python package you are using ?
`pip3 list | grep -i mongo`
