### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by DuckSound0** [Acceis/leakScraper#8]
Is the project still maintained? Following your installation guide I get multiple errors and while running leakScraper.py and going to port 8080 I get error 500.

Here is the error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/dist-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.9/dist-packages/bottle.py", line 3688, in wrapper
    result = func(*args, **kwargs)
  File "/home/parrot/Downloads/leakScraper/leakScraper.py", line 58, in index
    count = credentials.count()
  File "/usr/lib/python3/dist-packages/pymongo/collection.py", line 1865, in count
    return self._count(cmd, collation, session)
  File "/usr/lib/python3/dist-packages/pymongo/collection.py", line 1664, in _count
    return self.__database.client._retryable_read(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1460, in _retryable_read
    server = self._select_server(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 65267068bccd10bc362b42fd, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
127.0.0.1 - - [11/Oct/2023]  "GET / HTTP/1.1" 500 741
127.0.0.1 - - [11/Oct/2023] "GET /favicon.ico HTTP/1.1" 404 742
`

Edit: It seems like count is deprecated.

**Comment by Masriyan** [comment]
<img width="2032" alt="Screenshot 2023-11-28 at 11 06 39 AM" src="https://github.com/Acceis/leakScraper/assets/15161949/bdf8a525-c535-4b03-85f4-0760e98c4739">

i get the same

**Comment by saladandonionrings** [comment]
Hello, I have made some modification about this project (i had a lot of errors too) and added functionalities : https://github.com/saladandonionrings/leaky
